"""email

Revision ID: 449b1c97205f
Revises: 
Create Date: 2023-06-28 18:30:00.014835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449b1c97205f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
